# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
incremental: true


title: Prose.io Hilton Pogs
email: info@klishgroup.com
description: > # this means to ignore newlines until "baseurl:"
  Hilton Pogs written using Prose.io and GitHub Pages.

baseurl: "/prose-pogs" # the subpath of your site, e.g. /blog

# url: "http://www.klishgroup.com" # the base hostname & protocol for your site
url: http://klishgroup.github.io/prose-pogs

twitter_username: jekyllrb
github_username:  kgnd

# Build settings
markdown: kramdown
